version: '3.7'
services:
  web:
    stdin_open: true
    tty: true
    container_name: frontend
    build:
      context: .
      dockerfile: ./Dockerfile.app
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
        PORT: 8010
    volumes:
      - ./:/opt/app
    ports:
      - '8010:8010'
    env_file:
      - .env-docker
    environment:
      PORT: 8010
    # healthcheck:
    #   test: curl --fail frontend:8010/api/health || exit 1
    #   interval: 5s
    #   retries: 5
    #   start_period: 20s
    #   timeout: 10s
    # networks:
    #   - backend-network

# networks:
#   backend-network:
#     external: true
