version: '3.7'
services:
  web:
    stdin_open: true
    tty: true
    container_name: backend
    build:
      context: .
      dockerfile: ./Dockerfile.app
      args:
        USER_ID: "${USER_ID:-1000}"
        GROUP_ID: "${GROUP_ID:-1000}"
        PORT: 8011
    volumes:
      - ./:/opt/app
    ports:
      - '8011:8011'
    env_file:
      - .env-docker
    environment:
      PORT: 8011
    healthcheck:
      test: curl --fail backend:8011/forms || exit 1
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s
    networks:
      - backend-network

networks:
  backend-network:
    external: true
