version: '3.7'
services:
  postgresdb:
    container_name: postgresdb
    image: postgres
    restart: always
    ports:
      - '5432'
    volumes:
      - /var/lib/postgresql/data
    networks:
      - backend-network
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      retries: 5
      start_period: 20s
      timeout: 10s  

networks:
  backend-network:
    name: backend-network
